version: '3.5'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: frontend
    environment:
      - PORT=5000
    volumes:
      - .:/app/
    networks:
      - semapps
    ports:
      - "5000:5000"
    expose:
      - "5000"
    command: bash -c "npm rebuild && npm install && npm run bootstrap && npm start"

networks:
  semapps:
    name: semapps_network
