version: '3.5'
services:
  fuseki:
    image: semapps/jena-fuseki-webacl
    container_name: fuseki
    volumes:
      - ./data/fuseki:/fuseki
      - ./data/staging:/staging
    ports:
      - "3030:3030"
    expose:
      - "3030"
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    build:
      context: ./middleware
      args:
        - SELECTED_BRANCH=master
        - SELECTED_DIR=src/middleware/boilerplates/pair-ldp-server
    container_name: middleware
    depends_on:
      - fuseki
      - redis
    volumes:
      - ./middleware/logs:/app/logs
      - ./middleware/actors:/app/actors
      - ./middleware/jwt:/app/jwt
      - ./middleware/uploads:/app/uploads
    networks:
      - semapps
    ports:
      - "3000:3000"
    expose:
      - "3000"

  frontend:
    build:
      context: ./frontend
      args:
        - SELECTED_BRANCH=master
        - SELECTED_DIR=src/frontend/boilerplates/archipelago
    container_name: frontend
    networks:
      - semapps
    ports:
      - "5000:5000"
    expose:
      - "5000"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ./data/redis:/data
    networks:
      - semapps
    command: ["redis-server", "--appendonly", "yes"]

networks:
  semapps:
    name: semapps_network
